### ISSUE TITLE
[ERROR] TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mwmaleks** [kunklejr/node-db-migrate#142]
Hi, everybody! When runing migration it throws the error TypeError: Cannot read property 'name' of undefined from db-migrate/lib/migrator.js:125:66 if 'up' and form 159:66 if 'down'. It seems to be async.forEachSeries's callback receives empty parameter 'migration' . The only first migration of a list completes.

**Comment by wzrdtales** [comment]
Can you post the migrations which are failing?

**Comment by wzrdtales** [comment]
Seems to be fixed in the newest, can't reproduce this.

Feel free to reopen if this error still occurs and post a log and details about your used migrations and setup
