### ISSUE TITLE
Camel-case column names aren't respected for Postgresql

### ISSUE THREAD

**Issue by seanami** [kunklejr/node-db-migrate#155]
I ran into an issue where a downward migration failed to remove a column on the database that an upward migration created. Here's the migration:

```javascript
exports.up = function(db, callback) {
  db.addColumn('invitations', 'lastAccessed', { type: type.DATE_TIME }, callback);
};

exports.down = function(db, callback) {
  db.removeColumn('invitations', 'lastAccessed', callback);
};
```

And the error that I get is:

```
[ERROR] error: column "lastaccessed" of relation "invitations" does not exist
```

As you can see, the capital A of the column name is lost, and so Postgresql complains that the column doesn't exist.

I think I found the underlying issue, which is that if your column names (and table names) aren't all lower case, then you have to put quotes around the name in order for Postgres to respect the case. I guess some of the other queries in the driver do this, but not the removeColumn query. I looked through the driver and it looks like some other queries might have the same issue. Maybe the column names should just always be quoted? (Or maybe I should be using lower-case column names and then converting to camelCase...)

(I'm open to making a pull request for this, but I wanted to discuss it first since I'm not entirely certain that quoting column and table names would actually be a good thing to do.)

**Comment by wzrdtales** [comment]
related to #204
