### ISSUE TITLE
Feature Request: support pg-js

### ISSUE THREAD

**Issue by morefromalan** [kunklejr/node-db-migrate#171]
pg-js (pure javascript postgres driver) uses same interfaces as pg, but without c-binding.  It's more portable and should be a quick fix to support it as an option.  

I'm happy to put the code in if you want to weigh in on your preferred architecture: where should option to use pg vs pg-js go?

**Comment by wzrdtales** [comment]
Closed in favour of incoming external drivers.

refer to #227
