### ISSUE TITLE
How to drop a sequence?

### ISSUE THREAD

**Issue by countcain** [kunklejr/node-db-migrate#190]
In postgresql, I created a sequence. The db object have a method to dropTable. But when it comes to sequence, I could not find a way to drop it. Do this project have this function implemented?
Thanks!

**Comment by wzrdtales** [comment]
@countcain Are you asking how to create a serial sequence of instructions?
This would be already documented here:
https://github.com/kunklejr/node-db-migrate#creating-migrations

If not please provide more information and/or examples what you're trying to do.
Thanks

**Comment by wzrdtales** [comment]
Dropping sequences was already implemented and is part of v0.9.x
