### ISSUE TITLE
you can define the character?

### ISSUE THREAD

**Issue by alfa30** [kunklejr/node-db-migrate#191]
When loading values ​​in the table or database I can not set the charset.

**Comment by wzrdtales** [comment]
@alfa30 Could give a more thorough explanation, of when you want to define the encoding?

**Comment by wzrdtales** [comment]
Asked for response, there was no response so far. Thus I close this, as I clearly don't understand what exactly you want to be solved.

Feel free to reopen with a more thorough explanation
