### ISSUE TITLE
db-migrate takes very long time to exit

### ISSUE THREAD

**Issue by gramakri** [kunklejr/node-db-migrate#193]
Just testing out db-migrate for the first time. I have a noop migration.

exports.up = function(db, callback) {
    callback(null);
};

The above takes 1m30secs to complete. Note that 'No migrations to run' is printed immediately. It just takes a long time to exit.

time ./node_modules/.bin/db-migrate up
[INFO] No migrations to run
[INFO] Done

real	1m0.439s
user	0m0.142s
sys	0m0.028s

**Comment by wzrdtales** [comment]
Can't verify this, which node version do you used? Maybe already fixed?

```shell
[tobi@tobi:node-db-migrate master*]$ time node bin/db-migrate down
[INFO] Defaulting to running 1 down migration.
[INFO] Processed migration 20150201123858-test
[INFO] Done

real	0m0.346s
user	0m0.130s
sys	0m0.013s
[tobi@tobi:node-db-migrate master*]$ time node bin/db-migrate up
[INFO] Processed migration 20150201123858-test
[INFO] Done

real	0m0.232s
user	0m0.133s
sys	0m0.007s
```

**Comment by wzrdtales** [comment]
closed as not responding, feel free to reopen.
