### ISSUE TITLE
Foreign key

### ISSUE THREAD

**Issue by magmel48** [kunklejr/node-db-migrate#199]
Please, provide information about making foreign key without using raw sql statements (I mean js-way). It's important feature for PostgreSQL

**Comment by wzrdtales** [comment]
@magmel48 
I see, this is missing, will add this to the documentation.

Unfortunately foreign keys are not yet implemented for postgres.
There is a pull request open for this https://github.com/kunklejr/node-db-migrate/pull/181

I will see that this will merged soon.
