### ISSUE TITLE
createdb db_migrate_test gives command not found

### ISSUE THREAD

**Issue by toymachiner62** [kunklejr/node-db-migrate#206]
I'm following your instructions for developing on this project and I'm getting this error.

```sh
$ createdb db_migrate_test
-bash: createdb: command not found
```

Is there a global package I need to install to use the command `createdb`?

**Comment by wzrdtales** [comment]
This should be automatically available, as far as you have installed
postgres.

To note, this notices are from jeff, I'm currently reworking all tests
with lab. But this still takes some time.


Am 05.02.2015 um 17:38 schrieb Tom Caflisch:

**Comment by toymachiner62** [comment]
Oh i don't have postgres installed. I'll do that. 

You're reworking the tests with lab? Like for testing the hapi framework? https://www.npmjs.com/package/lab

**Comment by wzrdtales** [comment]
yes exactly

**Comment by toymachiner62** [comment]
Why would you do that if you're not using the hapi framework? I'd suggest using Mocha if you're rewriting the tests. Lab is based on it, but is specificially built for the hapi framework. node-db-migrate has nothing to do with hapi.

**Comment by wzrdtales** [comment]
You must not use hapi to use lab, they're not connected and lab And as you already said, lab has oriented much at mocha. But there are some things that are not available from mocha itself, controlable parallelism is not for example, correct me if I'm false and this is now a core component of mocha. Also I like the clean and simpleness, is there a specific reason why you would choose mocha over lab?

**Comment by toymachiner62** [comment]
So i can't answer about controlable parallelism b/c I don't know what that means, but i've used both lab and mocha pretty extensively and Mocha is actually a cleaner approach IMO b/c you can just use `describe` and `it`, while with lab you need to do `var lab = exports.lab = Lab.script();` and then use `lab.experiment` and `lab.test`.

Mocha also seems to have better handling for async and promises than lab.

Mocha also has a built in `-w` or "watch" flag so you can watch a test file for changes and automaticlly re-run the test.

Mocha also has a simple things like using `it.only` and `it.skip` while with lab you have to pass in an extra argument like `{skip: true}`

**Comment by toymachiner62** [comment]
From a guy who has used both, and continues to use both for different purposes - mocha for all my lib stuff and lab for all my hapi stuff, i'd recommend mocha over lab for your lib, unless you have a good reason against this.

**Comment by wzrdtales** [comment]
You can also do this to make it look like bdd

```javascript
var Code = require('code');
var Lab = require('lab');
var lab = exports.lab = Lab.script();
 
var describe = lab.describe;
var it = lab.it;
var before = lab.before;
var after = lab.after;
var expect = Code.expect;
```
And then just use 
Also documented in the lab doc.

The reason I want to use lab is basically because of the controlable parallelism. As I can pass in the option: { parallel: true } and control like this every single test or a whole suit to run parallel or not. Thats quite useful, also I could easily switch from lab to mocha without much work.

The watch flag is pretty useful, but nothing what I haven't right now. I have a standard gruntfile and use facebooks watchmen to trigger tests on changes.

I will think about your recommendation, but one thing left: Lab is definitely not only for testing hapi ;)

**Comment by wzrdtales** [comment]
Question answered
