### ISSUE TITLE
db-migrate command not found

### ISSUE THREAD

**Issue by toymachiner62** [kunklejr/node-db-migrate#210]
I'm trying to follow the README exactly to use this package.

If i run `$ npm install db-migrate --save` and then run any `$ db-migrate` command I get command not found. Does db-migrate need to be installed globally or what am I doing wrong?

```sh
$ db-migrate create add-pets
-bash: db-migrate: command not found
```

**Comment by toymachiner62** [comment]
Disregard this. It seems to be working now, but I get the error `[ERROR] Error: Could not find database config file '/Users/tomcaflisch/Sites/test-db-migrate/database.json'` which is a good error message, but I don't see anything in the README about neededing to create a database.json file unless wanting to specify it's location or to use different environments.

Do you think the README should be updated to make it more obvious that a database.json file is necessary?

**Comment by wzrdtales** [comment]
Actually this is already covered here:
https://github.com/kunklejr/node-db-migrate#configuration

The problem with db-migrate, the usage as global and local module is something I'm already working on at the moment.

Also I will move the docs from the readme into a more structured order, so anyone may be able to find the answere to his questions faster.

**Comment by wzrdtales** [comment]
But yeah, It should be a part of the usage headline mentoining there is a need for the database.json

**Comment by wzrdtales** [comment]
related to #138

**Comment by Termato** [comment]
Hi wzrdtales, I was wondering if it would be possible to put in the readme.md that you need to have the database.json file. I agree with toymachiner that it is a good message but it would have been much easier to just have it in the readme.md. Just my two cents. Thanks!

**Comment by wzrdtales** [comment]
@Termato Hey, sry for having trouble, but the documentation is now completely on read the docs and there you can find this information.

May be we should move this part https://github.com/db-migrate/node-db-migrate#resources-and-usage-instructions a bit more to the top to make the users aware to actually read the docs.

**Comment by Termato** [comment]
Yea, I can definitely see why you wouldn't want to duplicate information. Moving it to the top, or at least higher, would definitely help. At least above the driver information.

I was confused at first because the previous link: https://github.com/kunklejr/node-db-migrate#configuration took me to the readme instructions. I think that anchor may have been removed?

Anyways, this clears it up, it was just confusing at first. Thank you.

**Comment by wzrdtales** [comment]
Ic, yes definitely, this needs to be updated. This anchor was there before the docs have been moved yes.
