### ISSUE TITLE
Transaction based migrations

### ISSUE THREAD

**Issue by wzrdtales** [kunklejr/node-db-migrate#216]
Implement transactions per migration, thus everything gets rolled back on failure.

**Notes:**
Make it possible to deactivate transactions within the migrations.
Drivers gets flagged with transaction capability

**Comment by jarwol** [comment]
Looking forward to this feature.  Very easy to get your DB into a bad state when a migration you're testing fails halfway through.

**Comment by wzrdtales** [comment]
Actually mysql doesn't support DDL Transactions for now. Luckily MariaDB is going to support this soon:

https://mariadb.atlassian.net/browse/MDEV-4259

Thus this issue is closed as transactions are now built in, but mysql still wont rollback any ddl actions such as drop table.

Nevertheless, migrations will get more intelligent in the next versions of db-migrate. So db-migrate knows about states, tables and metadata.
But this still wont fix a deleted table and restore the data within this, may be I will offer a dump table action on all ddl actions, which can optionally be activated.
