### ISSUE TITLE
---env option is not working

### ISSUE THREAD

**Issue by toymachiner62** [kunklejr/node-db-migrate#220]
I can succcessfully set the environment by using the `-e` option, but the `---env` option is not working:

example:
```sh
$ db-migrate up ---env="myEnv"
[ERROR] Error: Environment(s) 'dev, development' not found.
```

**Comment by wzrdtales** [comment]
Can't reproduce this, maybe you can track this down via node debug?

**Comment by toymachiner62** [comment]
Maybe it's a difference with windows/*nix. I'll try to track it down.

**Comment by wzrdtales** [comment]
Haven't tested it yet under windows, but I would wonder if this is the reason.

It's strange you enter myEnv as environment and it trys to find dev and development.

**Comment by toymachiner62** [comment]
I'm working on OSX. I thought you were on windows the other day.

**Comment by wzrdtales** [comment]
Well no, I'm only on Windows if I don't want to work with my System i.e. gaming... . Using Arch Linux here ;)

**Comment by wzrdtales** [comment]
So however, still can't reproduce this. Would be great if you could deliver more information what exactly is happening.

**Comment by toymachiner62** [comment]
I'll get some more specifics on this and get back to you.

**Comment by toymachiner62** [comment]
Doh!. If you look closer at the error i posted, I had used 3 dashes instead of two. User error.
