### ISSUE TITLE
How to run all down migrations without specifying a max

### ISSUE THREAD

**Issue by toymachiner62** [kunklejr/node-db-migrate#221]
I notice that when I just run 

```sh
$ db-migrate down -e undefined
[INFO] Defaulting to running 1 down migration.
[INFO] Processed migration 20150211200908-add-authorized-users
[INFO] Done
```

it defaults to 1 down migration. I see there is a `-c` option to specify the count of migrations I want to run, but is there a way to specify "all" down migrations? And should there be or is that a rediculous request?

**Comment by wzrdtales** [comment]
There is currently no such thing like -c all. I also wondered frist about the behavior of down, but I don't think that the default behavior of migration only a single down is wrong.

I would suggest adding reset, to literally reset all migrations.

**Comment by toymachiner62** [comment]
Ahh i like the idea of reset. It's like Ruby on Rails `rake db:migrate:reset` command.
