### ISSUE TITLE
Is this variable necessary?

### ISSUE THREAD

**Issue by toymachiner62** [kunklejr/node-db-migrate#223]
Looking at the code that is generated for migrations, is the "type" variable necessary? I don't see where it's used, and I don't use it in any of my migration files: https://github.com/kunklejr/node-db-migrate/blob/master/lib/migration.js#L81

**Comment by wzrdtales** [comment]
Yes of course it is ;)

there are generic datatypes which should be used in the best case. They
can translate to other datatypes if you switch between databases and
this databases have different datatypes which fullfil the same thing.

Am 12.02.2015 um 15:36 schrieb Tom Caflisch:

**Comment by wzrdtales** [comment]
Unfortunately I see, this is also not documented...
