### ISSUE TITLE
v0.9.0, v0.9.1: migrate up crashes with sqlite3

### ISSUE THREAD

**Issue by gramakri** [kunklejr/node-db-migrate#226]
In lib/driver/base.js, allLoadedMigrations calls "this.connection.query.apply(this.connection, sql);". However the sqlite3 connection object does not have a method named query (https://github.com/mapbox/node-sqlite3/wiki/API).It has only Database#run. 

0.8.0 and below used to call Base.runSql which was implemented as run() in sqlite3 driver and works fine.

**Comment by SPY** [comment]
have the same problem.
this code looks odd https://github.com/kunklejr/node-db-migrate/blob/master/lib/driver/base.js#L293
i think it should be call instead of apply or just this.connection.query(sql)

**Comment by wzrdtales** [comment]
I see, patch is incoming

**Comment by wzrdtales** [comment]
Fixed and also fixed some failures I found while fixing this.

**Comment by gramakri** [comment]
I can confirm this is fixed.

**Comment by wzrdtales** [comment]
Thanks for reporting :)
