### ISSUE TITLE
Will the real callback please stand up?

### ISSUE THREAD

**Issue by dalemanthei** [kunklejr/node-db-migrate#229]
The callback variable is defined twice in mongodb.js _run function:

![mongodb_js_ _db-migrate](https://cloud.githubusercontent.com/assets/6266984/6229208/d36e916a-b67a-11e4-9ece-e540fe58eb88.png)

**Comment by wzrdtales** [comment]
Have clearly overseen this while checking the merge request, thanks for reporting. However _makeParamArgs returns as [2] element the last element of arguments. So the callback is still the same.

@toymachiner62 Can you tell me why you used defined params and arguments together here? Does there exist a reason for that, or may I just remove this and use the callback provided already.

**Comment by toymachiner62** [comment]
I didn't realize i did that. I made the arguments explicitly passed in b/c I hate the magical-ness of not having them passed into the function.

I didn't mean to do both though.

**Comment by wzrdtales** [comment]
I also like it better to define them in the function, I will change this to not use arguments in this case.
