### ISSUE TITLE
SQL generated from user table migration added extra set of quotes

### ISSUE THREAD

**Issue by veswill3** [kunklejr/node-db-migrate#234]
Here is my migration for my users table.
```js
var dbm = require('db-migrate');
var type = dbm.dataType;

exports.up = function(db, callback) {
  db.addColumn('"user"', '"lowcaseEmail"', {
    type: 'text',
    unique: true
  },function(err) {
    if (err) return callback(err);
    db.runSql('UPDATE "user" SET "lowcaseEmail" = lower(email);', callback);
  });
};

exports.down = function(db, callback) {
  db.removeColumn('"user"', '"lowcaseEmail"', callback);
};
```
This runs just fine in `db-migrate@0.8.0` but in `db-migrate@0.9.3` it did not. Here is the output:
```
[SQL] BEGIN;
[SQL] ALTER TABLE ""user"" ADD COLUMN "lowcaseEmail" TEXT  UNIQUE
[SQL] UPDATE "user" SET "lowcaseEmail" = lower(email);
[SQL] INSERT INTO "migrations" (name, run_on) VALUES ($1, $2) [ [ '/20150218042651-add-lowcaseEmail-column-to-User',
    Tue Feb 24 2015 00:36:23 GMT+0000 (UTC) ] ]
```
I am guessing the problem is that user is double wrapped in quotes on the ALTER TABLE line.
Is this a bug or did the syntax for writing the migration change?

**Comment by wzrdtales** [comment]
db.removeColumn('"user"', '"lowcaseEmail"', callback);

You should not escape within db.removeColumn or any other methods. db-migrate will escape for you  comaptible for your choosed database system automatically.

**Comment by wzrdtales** [comment]
This is also due to the fact, that db-migrate should escape everything for you. But this wasn't consequent everywhere before 0.9.0.

This is the reason why your old migrations work on 0.8.0 but not on 0.9.0. Just remove your quoting as db-migrate does this now for you.:

   db.addColumn('user', 'lowcaseEmail', {

**Comment by tobalsgithub** [comment]
Did that change recently? The user table is a reserved word in PostgreSQL, and when we don't escape the table name, the migrations fail. On version 0.8.0 this all worked fine. Only when upgrading to 0.9.3 did we hit this issue.

**Comment by wzrdtales** [comment]
I know that it is a reserved name, as pointed out:
db-migrate will now do the escaping for you. You don't need to look out for special names that are reserved by some db. This applies now also to all other drivers. As long as you don't use runSql you don't need to escape yourself anymore.

See also:

https://github.com/kunklejr/node-db-migrate/blob/master/lib/driver/pg.js#L238-L287

https://github.com/kunklejr/node-db-migrate/blob/master/lib/driver/pg.js#L37-L45

**Comment by wzrdtales** [comment]
That in 0.8.0 there was in some cases no automatic escaping was not intended so. The other drivers already escaped themselfes.

**Comment by tobalsgithub** [comment]
Sorry, missed your second post. That all makes sense. 

We just need to go back and update our migration syntax to match the new version.

**Comment by wzrdtales** [comment]
Shouldn't be hard task so :) little bit of regex search and replace

**Comment by veswill3** [comment]
Thanks @wzrdtales!

**Comment by wzrdtales** [comment]
I suggest you update to 0.9.4, as you may run into this failure:
https://github.com/kunklejr/node-db-migrate/issues/235

also. Just published a bugfix for this.
