### ISSUE TITLE
Upgraded from 0.5.4 to 0.9.2, new migrations are prefixed with slash, old migrations will not migrate down

### ISSUE THREAD

**Issue by mpalmerlee** [kunklejr/node-db-migrate#235]
We recently upgraded from 0.5.4 to 0.9.2 and noticed that new migrations in the migrations table are prefixed with a forward slash:

old:
20150121183613-target-token

new:
/20150218150557-random

We generate these migrations like so:
./node_modules/db-migrate/bin/db-migrate create migration-name --migrations-dir lib/migrations --config  config/config.json

and run up like so:
./node_modules/db-migrate/bin/db-migrate up --migrations-dir lib/migrations --config config/config.json -e local

and run the down:
./node_modules/db-migrate/bin/db-migrate down --migrations-dir lib/migrations --config config/config.json -e local

The problem is that now with db-migration 0.9.2, when we try to do a "down" on an old migration without the starting forward slash, it seems that it will run run the down migration but won't remove it from the migrations table.  Using verbose it's doing this:
[SQL] DELETE FROM `migrations` WHERE name = ? [ [ '/20150121183613-target-token' ] ]

**Comment by wzrdtales** [comment]
I see, well this wasn't exactly intended:
https://github.com/kunklejr/node-db-migrate/blob/master/lib/migrator.js#L38

And was introduced due to:
https://github.com/kunklejr/node-db-migrate#multiple-migration-scopes

I will create a patch for this.

**Comment by wzrdtales** [comment]
bugfix is now online in the newest version 0.9.4 published a second ago

thanks for reporting

**Comment by mpalmerlee** [comment]
Awesome! Thanks for the fast resolution!

**Comment by wzrdtales** [comment]
No problem, don't hesitate to open issues on problems.
