### ISSUE TITLE
Error: Cannot enqueue Quit after invoking quit 

### ISSUE THREAD

**Issue by gayanhewa** [kunklejr/node-db-migrate#238]
I keep on getting this error although the migrations run smoothly. How do I get rid of this and whats the reason behind it ?

**Comment by wzrdtales** [comment]
Hi @gayanhewa 
I can't help you if you don't specify what exactly the failure is plus, which version of node you use and a log from a run in the verbose mode (-v).

**Comment by wzrdtales** [comment]
Also please add details about your configuration.

**Comment by gayanhewa** [comment]
This is how the error looks like : 

~~~
[ERROR] Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:193:16)
    at Protocol._enqueue (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Connection.query (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/Connection.js:185:25)
    at Class.Base.extend.all (/usr/lib/node_modules/db-migrate/lib/driver/mysql.js:406:34)
    at Class.Base.extend.allLoadedMigrations (/usr/lib/node_modules/db-migrate/lib/driver/mysql.js:416:10)
    at Function.Migration.loadFromDatabase (/usr/lib/node_modules/db-migrate/lib/migration.js:217:10)
    at /usr/lib/node_modules/db-migrate/lib/migrator.js:103:17
    at /usr/lib/node_modules/db-migrate/lib/migration.js:211:5
    at Object.oncomplete (fs.js:107:15)
~~~

Output from the db-migration up -v

~~~
[INFO] Using dev settings: { host: 'localhost',
  user: 'root',
  password: '******',
  database: 'db',
  driver: 'mysql',
  multipleStatements: true }
[INFO] require: ./mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /vagrant/api/db-migrations/migrations
[INFO] loading migrations from database
~~~

**Comment by gayanhewa** [comment]
NPM Version - 1.4.28
DB-Migrate - ^0.9.7

Server : Ubuntu 14.04 -/ Vagrant instance.

**Comment by wzrdtales** [comment]
Ok, in your last run you didn't run into a failure. I must be able to reproduce this bug to fix it.
Cannot enqueue Query after fatal error. Sounds like there went something wrong just before.

Could you please also deliver your node.js version?

Can you provide me more to reproduce this? Migrations with which this error is raised for example?

**Comment by gayanhewa** [comment]
Nodejs - v0.10.33

How do I know for which migration this happened ? , I have a few migrations and it happens even if I run just one.

**Comment by wzrdtales** [comment]
Does this happen with every of your migration? Try up -count 1 and look if this happens to all migrations even they're started single.

**Comment by gayanhewa** [comment]
Yes. if I use the flag -c 1 it will happen aswell , but just once.

**Comment by wzrdtales** [comment]
Well I still can't reproduce this, could you please post one of your migrations. Of course should delete everything that's maybe confidential.

**Comment by wzrdtales** [comment]
I'm away for some hours now, so I wont answere from now on.

Please provide enough information to make it possible to **anyone** to reproduce your issue. Without the possibility to reproduce no one can help you and the bug keeps unsolved.

So please post:

* Used configuration tweaks.
* How does db-migrate gets invoked
* The full log of the full run where the error occurs in verbose mode, also including the queries generated. Replace confidential informations if needed.
* Post your migrations

Also answere these common questions:

* Do you have used db-migrate before?
* Does this error exist in an earlier release?

Thanks

**Comment by gayanhewa** [comment]
Hi, Thank you for the help. Here is what I could gather from my findings : 

The Error doesn't result in a failure. Its more connected to node-mysql rather the db-migrate module. 

http://stackoverflow.com/questions/23328496/node-js-mysql-cannot-enqueue-a-query-after-calling-quit

I was able to come down to the point where , after the migration is processed and a onComplete call back attempts to close the connection with the db and if it is already close there will be an error popping out. 

~~~
function onComplete(migrator, originalErr) {
  migrator.driver.close(function(err) {
    assert.ifError(originalErr);
    assert.ifError(err);
    log.info('Done');
  });
}
~~~

For now I can suppress the erros from here. But not ideal.

verbose output : http://pastebin.com/RVkUP1B2

**Comment by wzrdtales** [comment]
```
[INFO] Processed migration 20150304151952-create-device-table
[INFO] Processed migration 20150304151952-create-device-table
```

Could you show me this migration and the migration?

 Normaly db-migrate shouldn't execute this twice. And also shouldn't write that much entries to the migrations table.

It definitely seems that you made a mistake in your migrations. I suspect you're calling the callback multiple times.

**Comment by gayanhewa** [comment]
@wzrdtales  http://pastebin.com/jEcHdfcF

**Comment by gayanhewa** [comment]
You are right :+1:  the issue was with me trying to execute multiple statements within a single migration.

**Comment by gayanhewa** [comment]
Thank you :+1:

**Comment by wzrdtales** [comment]
You can call mutiple statements within a single migrations, but you have to call one by one in the callback of the last one and then finally call the callback ;)

And no problem

The good news:
This is getting easier, v0.10.x will introduce Promises support.

**Comment by gayanhewa** [comment]
Awesome :bow:
