### ISSUE TITLE
Missing 'var' in template

### ISSUE THREAD

**Issue by forstermatth** [kunklejr/node-db-migrate#240]
When creating a new migration, the template is missing a 'var' keyword. I think it might be [here](https://github.com/kunklejr/node-db-migrate/blob/master/lib/migration.js#L56). 
I don't see it right away as I am using the `--sql-file` option to keep the database code in SQL, and I don't look at the top level migration file.

This does't affect db-migrates ability to run on my local machine, but it fails (`dbm not defined`) during our deploy script that is run through continuous integration, which in return fails to migrate the database and causes problems.

This is fixed by adding 'var' in front of the first line in the migration file (in the template here: https://github.com/kunklejr/node-db-migrate/blob/master/lib/migration.js#L56).

**Comment by wzrdtales** [comment]
No it's not. This is clearly intended!

This is the only possibility to share down requires to the migrations without having to set NODE_PATH to the global module directory.

**Comment by wzrdtales** [comment]
It gets defined in the db-migrate bin
https://github.com/kunklejr/node-db-migrate/blob/master/bin/db-migrate#L19-L20

This will be done through the API also, which gets introduced in v0.10.x, yet there isn't a real support to use db-migrate as a module.
