### ISSUE TITLE
Down migrations with mongodb

### ISSUE THREAD

**Issue by fleg** [kunklejr/node-db-migrate#242]
Down migrations are **NOT** run in reverse run order with mongodb driver

example:
```
fleg@fleg-pc:~$ db-migrate up
[INFO] Processed migration 20150312073909-users
[INFO] Processed migration 20150312074623-users-populate
[INFO] Processed migration 20150312080314-users-populate-2
[INFO] Done
```

```
fleg@fleg-pc:~$ db-migrate down -c 3
[INFO] Processed migration 20150312073909-users
[INFO] Processed migration 20150312074623-users-populate
[INFO] Processed migration 20150312080314-users-populate-2
[INFO] Done
```

Probably because of missing sorting by `run_on` field in [allLoadedMigrations](https://github.com/kunklejr/node-db-migrate/blob/bf380ef32c22716620c9f5ac2001537d4f7b8e25/lib/driver/mongodb.js#L326) function

**Comment by wzrdtales** [comment]
@fleg Bugfix published in v0.9.9.

Thank you for reporting
