### ISSUE TITLE
db-migrate sitting on "done"...

### ISSUE THREAD

**Issue by mcandre** [kunklejr/node-db-migrate#74]
db-migrate appears to successfully execute migrations, but when it's done, it sits there without returning to the shell. I have to manually press Control+C to break out.

Trace:

	$ db-migrate up
	[INFO] Processed migration 20120828003940-add-users
	[INFO] Processed migration 20120830212635-add-approver-id-to-users
	[INFO] Processed migration 20120831174003-add-roles
	...
	[INFO] Processed migration 20130208181305-create-timecard-completions
	[INFO] Processed migration 20130211185210-add-managers-table
	[INFO] Processed migration 20130213194120-remove-invalid-facebook-list-posts
	[INFO] Done
	(blinking cursor forever)

System:

	$ db-migrate --version
	0.3.2

	$ specs node bash git os
	Specs:

	specs 0.2
	https://github.com/mcandre/specs#readme

	npm --version
	1.2.10

	node --version
	v0.8.19

	bash --version
	GNU bash, version 3.1.0(1)-release (i686-pc-msys)
	Copyright (C) 2005 Free Software Foundation, Inc.

	git --version
	git version 1.8.0.msysgit.0

	systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
	OS Name:                   Microsoft Windows XP Professional
	OS Version:                5.1.2600 Service Pack 3 Build 2600

**Comment by wzrdtales** [comment]
Closed as old and probably resolved.

Feel free to reopen this issue and post more details about your setup and used migrations to solve your problem entirely.
